defmodule MobMishka.Migrate do
  @moduledoc """
  Pure implementation behind `mix mob_mishka.migrate`.

  Existing Mob apps generated by `mob_new < 0.5.x` have ~75 vendored
  Mishka composite files under `lib/<app>/components/mishka_*.ex`, a
  fenced `config :mob, :extra_tags` block in `config/config.exs`, and a
  `<App>.Showcase.register_all()` call in `on_start` — all of which
  become redundant once the app depends on `:mob_mishka` and the mob
  version supports plugin-manifest tag discovery (MOB-247).

  This module analyses a caller's tree and produces a list of
  `t:action/0` values the caller can preview and apply. Kept pure so
  the mix task is a thin CLI wrapper and every real decision is
  testable.
  """

  @typedoc """
  One migration step:

    * `{:remove_vendored_composite, path, {tag, plugin_module}}` — a
      file at `path` is byte-identical to the plugin-shipped default
      for `plugin_module` (registered as `tag`). Safe to delete.

    * `{:keep_user_edited_composite, path, {tag, plugin_module}}` —
      file diverges from the plugin's default. Skipped; the user's
      edits are preserved and the plugin's version is superseded
      via `override_namespace` when configured.

    * `{:unrecognized_composite, path}` — a `mishka_*.ex` file in
      `lib/<app>/components/` that doesn't match any composite the
      plugin ships. Left alone.

    * `{:remove_extra_tags_block, path}` — `config/config.exs` still
      carries the fenced compatibility block. Removable if the app's
      mob dep is past MOB-247.
  """
  @type action ::
          {:remove_vendored_composite, Path.t(), {atom(), module()}}
          | {:keep_user_edited_composite, Path.t(), {atom(), module()}}
          | {:unrecognized_composite, Path.t()}
          | {:remove_extra_tags_block, Path.t()}

  @doc """
  Analyse `root` (a Mix project directory containing the app's
  `lib/`) and return a proposed list of `t:action/0` values. Reads
  files but writes nothing.

  Options:

    * `:app` — the target app's atom name. Required. Used to find
      `lib/<app>/components/` and normalise composite paths.
  """
  @spec plan(Path.t(), keyword()) :: [action()]
  def plan(root, opts) do
    app = Keyword.fetch!(opts, :app)
    components_dir = Path.join([root, "lib", Atom.to_string(app), "components"])

    plugin_lookup = plugin_lookup()

    composite_actions =
      if File.dir?(components_dir) do
        components_dir
        |> Path.join("mishka_*.ex")
        |> Path.wildcard()
        |> Enum.map(&classify_composite(&1, plugin_lookup))
      else
        []
      end

    config_actions = classify_extra_tags_block(Path.join([root, "config", "config.exs"]))

    composite_actions ++ config_actions
  end

  @doc """
  Apply the actions returned by `plan/2`. Writes to disk.

  Options:

    * `:remove_extra_tags` — when `false` (default), leaves the
      fenced `extra_tags` compatibility block alone; the app's mob
      dep may still need it. Pass `true` once the app has bumped past
      the mob release that ships MOB-247.
  """
  @spec apply([action()], keyword()) :: :ok
  def apply(actions, opts \\ []) do
    Enum.each(actions, &apply_one(&1, opts))
    :ok
  end

  @doc """
  Every `{tag, plugin_module}` the plugin registers, keyed by the
  underscore file basename (e.g. `"mishka_dialog"`) that a
  `mob_new`-generated vendored copy would have carried. Used by
  `plan/2` to align on-disk filenames to plugin composites.
  """
  @spec plugin_lookup() :: %{String.t() => {atom(), module()}}
  def plugin_lookup do
    Map.new(MobMishka.composites(), fn {_tag, module} = entry ->
      short = module |> Module.split() |> List.last() |> Macro.underscore()
      {short, entry}
    end)
  end

  # ── private ─────────────────────────────────────────────────────────

  defp classify_composite(path, lookup) do
    basename = Path.basename(path, ".ex")

    case Map.get(lookup, basename) do
      nil ->
        {:unrecognized_composite, path}

      {_tag, plugin_module} = entry ->
        if file_matches_plugin?(path, plugin_module) do
          {:remove_vendored_composite, path, entry}
        else
          {:keep_user_edited_composite, path, entry}
        end
    end
  end

  # A vendored copy is "byte-identical" to the plugin's default when
  # every non-empty line of the plugin file appears in the user's
  # file. This tolerates the app-namespace substitution
  # (`<App>.Components.Mishka*` vs `MobMishka.Components.Mishka*`)
  # that mob_new performs on generation, while still catching a real
  # user edit (an inserted line, a changed prop default, a swapped
  # helper call).
  defp file_matches_plugin?(user_path, plugin_module) do
    plugin_path = MobMishka.Gen.source_path(plugin_module)

    with true <- File.exists?(plugin_path),
         {:ok, plugin_src} <- File.read(plugin_path),
         {:ok, user_src} <- File.read(user_path) do
      user_normalised = normalise(user_src)
      plugin_normalised = normalise(plugin_src)
      user_normalised == plugin_normalised
    else
      _ -> false
    end
  end

  defp normalise(source) do
    source
    # Strip the app-namespace substitution `mob_new` performs on the
    # top-line `defmodule`. Everything past the module name is body
    # text and is compared verbatim.
    |> String.replace(
      ~r/defmodule [A-Za-z_.]+\.Components\.(Mishka[A-Za-z0-9_]+) do/,
      "defmodule <NS>.Components.\\1 do"
    )
    |> String.replace(
      ~r/alias [A-Za-z_.]+\.Components\.(Mishka[A-Za-z0-9_]+)/,
      "alias <NS>.Components.\\1"
    )
    |> String.split("\n", trim: false)
    |> Enum.map(&String.trim_trailing/1)
    |> Enum.join("\n")
  end

  # The MOB-252 fenced block in generated config.exs. Detected by the
  # sentinel comment mob_new emits above it — same string every
  # generated app carries, so it's a safe signature.
  @extra_tags_marker "`mob_mishka` supplies the `<Mishka…>` composite tags"

  defp classify_extra_tags_block(config_path) do
    with true <- File.exists?(config_path),
         {:ok, content} <- File.read(config_path),
         true <- String.contains?(content, @extra_tags_marker) do
      [{:remove_extra_tags_block, config_path}]
    else
      _ -> []
    end
  end

  defp apply_one({:remove_vendored_composite, path, _entry}, _opts) do
    File.rm!(path)
  end

  defp apply_one({:keep_user_edited_composite, _path, _entry}, _opts), do: :ok
  defp apply_one({:unrecognized_composite, _path}, _opts), do: :ok

  defp apply_one({:remove_extra_tags_block, path}, opts) do
    if Keyword.get(opts, :remove_extra_tags, false) do
      content = File.read!(path)
      # The block runs from the leading comment paragraph through the
      # closing `)` of the ~w sigil. Strip everything between the
      # marker line and the first `)` at column 0 that closes ~w.
      stripped = strip_extra_tags_block(content)
      if stripped != content, do: File.write!(path, stripped)
    end
  end

  # Strip from the block's leading comment paragraph through the ~w
  # closing `)`. Idempotent — a config.exs the user already cleaned
  # up passes through unchanged.
  defp strip_extra_tags_block(content) do
    marker = "\n# `mob_mishka` supplies the `<Mishka…>` composite tags"

    case String.split(content, marker, parts: 2) do
      [_only] ->
        content

      [head, tail] ->
        case String.split(tail, ~r/\n\)\n/, parts: 2) do
          [_incomplete] -> content
          [_block, rest] -> String.trim_trailing(head) <> "\n" <> String.trim_leading(rest)
        end
    end
  end
end
