defmodule Mix.Tasks.MobMishka.Migrate do
  @moduledoc """
  Migrate an existing Mob app off the pre-plugin Mishka vendoring shape.

      mix mob_mishka.migrate                    # dry run (default)
      mix mob_mishka.migrate --apply            # actually delete redundant vendored copies
      mix mob_mishka.migrate --apply --remove-extra-tags   # also strip the compat bridge

  Apps generated by `mob_new` before the MOB-252 change vendored ~75
  Mishka composite files into `lib/<app>/components/mishka_*.ex`, plus
  a fenced `config :mob, :extra_tags` block in `config/config.exs`.
  Once you depend on `{:mob_mishka, "~> 0.1"}`, those vendored copies
  are redundant — the plugin ships the same source.

  This task:

    * Deletes vendored composite files that are byte-identical to the
      plugin's default (after normalising the `<App>.Components.*` vs
      `MobMishka.Components.*` namespace substitution `mob_new`
      performs on generation).
    * Preserves user-edited copies — those still supersede the
      plugin's default via `config :mob_mishka, :override_namespace,
      <App>.Components`, so the eject/edit workflow keeps working.
    * Optionally strips the fenced `extra_tags` bridge from
      `config/config.exs` — only pass `--remove-extra-tags` once your
      app is on a mob release that ships plugin-manifest tag
      discovery (MOB-247). Otherwise the sigil will warn on
      `<Mishka…>` tags.

  Default is a dry run: prints the plan without touching disk. Pass
  `--apply` to actually make the changes.

  ## Options

    * `--apply` — write the changes to disk instead of previewing.
    * `--remove-extra-tags` — also strip the `config :mob, :extra_tags`
      compatibility block. Only safe once the mob dep floor is past
      MOB-247's release.
  """
  @shortdoc "Migrate an existing Mob app off the pre-plugin Mishka vendoring shape"

  use Mix.Task

  alias MobMishka.Migrate

  @impl Mix.Task
  def run(argv) do
    {opts, _positional} =
      OptionParser.parse!(argv,
        switches: [apply: :boolean, remove_extra_tags: :boolean]
      )

    app = Mix.Project.config()[:app]

    if not is_atom(app) or app == :mob_mishka do
      Mix.raise(
        "mob_mishka.migrate must be run from inside a Mix project that depends on :mob_mishka. " <>
          "Detected app: #{inspect(app)}"
      )
    end

    actions = Migrate.plan(".", app: app)
    print_plan(actions)

    cond do
      actions == [] ->
        Mix.shell().info("\nNothing to migrate — the app is already on the plugin shape.")

      opts[:apply] ->
        Migrate.apply(actions, remove_extra_tags: opts[:remove_extra_tags] || false)
        Mix.shell().info("\n* migration applied.")
        print_next_steps(opts)

      true ->
        Mix.shell().info("""

        Dry run — no files written. Re-run with `--apply` to make these changes.
        Add `--remove-extra-tags` once the app's mob dep is past MOB-247.
        """)
    end
  end

  defp print_plan(actions) do
    if actions == [] do
      :ok
    else
      Mix.shell().info("Planned migration:\n")

      Enum.each(actions, fn
        {:remove_vendored_composite, path, {tag, _}} ->
          Mix.shell().info("  [remove]   #{path}  (matches plugin's :#{tag})")

        {:keep_user_edited_composite, path, {tag, _}} ->
          Mix.shell().info(
            "  [keep]     #{path}  (edited copy; supersedes plugin's :#{tag} at boot)"
          )

        {:unrecognized_composite, path} ->
          Mix.shell().info("  [skip]     #{path}  (no matching plugin composite)")

        {:remove_extra_tags_block, path} ->
          Mix.shell().info(
            "  [strip*]   #{path}  (compat bridge; needs --remove-extra-tags to strip)"
          )
      end)
    end
  end

  defp print_next_steps(opts) do
    unless opts[:remove_extra_tags] do
      Mix.shell().info("""

      Not stripped yet: the fenced `config :mob, :extra_tags` block in
      `config/config.exs` remains a compatibility bridge. Once your mob
      dep is past the release that ships MOB-247, re-run:

          mix mob_mishka.migrate --apply --remove-extra-tags
      """)
    end
  end
end
